### ISSUE TITLE
Can't install flatpaks from mintinstall on 19

### ISSUE THREAD

**Issue by pharaszti** [linuxmint/mintinstall#195]
I can't install any flatpaks from mintinstall on Linux Mint 19 Cinnamon 64-bit. 

Example:
I tried to install "Atom" from mintinstall, I searched for it and "Atom" was found. When I clicked on it, it opened "Atom"'s page and gave me the following error message:
"An error occured. Could not locate 'runtime/org.freedesktop.Sdk/x86_64/1.6' in any registered remotes"

Same happens when I try to install Android Studio, Audacity and Spotify from flathub. Regular deb packages from the apt repositories install just fine.

The screenshot should make things clearer.

![mintinstall-flatpak-issue](https://user-images.githubusercontent.com/40702827/42112872-9f360210-7be9-11e8-8f46-1fa225e17252.png)

Thank you for addressing the issue. Have a nice day!

**Comment by mtwebster** [comment]
Fixed by:

308694d8 - `_flatpak.py: When fetch_remote_ref_sync() fails, fallback to building`
cdb955cb - `_flatpak.py: Return installed ref list without first trying to convert`

**Comment by ADepic** [comment]
I installed linux mint yesterday (fresh install no dual boot) and I get this exact error still.

**Comment by fabricI0** [comment]
I just installed a fresh copy of LM19 today and I can confirm the same error: "**Could not locate runtime **runtime/org.gnome.Platformx86_64/-- in any registered remotes**" where **--** stands for different numbers depending on the program you try to install.

**Comment by squid-f** [comment]
Hello all.
I confirm I have the same error on my recent install of LM19.
However, for nextcloud sync client for instance, I didn't get the error when I clicked on it just after the install. But, when I came back after having made the first system update, I got the error.
In case it helps.
Thanks for the great job!

**Comment by ADepic** [comment]
Hey hey hey, guys, please stop reporting problems on this closed issue.

The issue has moved here:

 #196
