### ISSUE TITLE
mininstall crashes when conducting a search LMDE 4

### ISSUE THREAD

**Issue by tmaleshafske** [linuxmint/mintinstall#275]
When conducting a search from mintinstall after inputting the third letter and it actually begins to search and then crashes. here is the output when running from terminal.

`tmaleshafske@yoga-260:~$ mintinstall
/usr/lib/linuxmint/mintinstall/mintinstall.py:700: DeprecationWarning: Gdk.Screen.get_monitor_at_point is deprecated
  monitor_number = screen.get_monitor_at_point(position.x, position.y)
/usr/lib/linuxmint/mintinstall/mintinstall.py:539: PyGIDeprecationWarning: Using positional arguments with the GObject constructor has been deprecated. Please specify keyword(s) for "schema" or use a class specific constructor. See: https://wiki.gnome.org/PyGObject/InitializerDeprecations
  self.settings = Gio.Settings("com.linuxmint.install")
MintInstall: Detected system architecture: 'x86_64'
Installer: User pkgcache is most recent, using it.
/usr/lib/linuxmint/mintinstall/mintinstall.py:779: PyGTKDeprecationWarning: Using positional arguments with the GObject constructor has been deprecated. Please specify keyword(s) for "label" or use a class specific constructor. See: https://wiki.gnome.org/PyGObject/InitializerDeprecations
  self.installed_menuitem = Gtk.MenuItem(_("Show installed applications"))
/usr/lib/linuxmint/mintinstall/mintinstall.py:788: PyGTKDeprecationWarning: Using positional arguments with the GObject constructor has been deprecated. Please specify keyword(s) for "label" or use a class specific constructor. See: https://wiki.gnome.org/PyGObject/InitializerDeprecations
  search_summary_menuitem = Gtk.CheckMenuItem(_("Search in packages summary (slower search)"))
/usr/lib/linuxmint/mintinstall/mintinstall.py:794: PyGTKDeprecationWarning: Using positional arguments with the GObject constructor has been deprecated. Please specify keyword(s) for "label" or use a class specific constructor. See: https://wiki.gnome.org/PyGObject/InitializerDeprecations
  search_description_menuitem = Gtk.CheckMenuItem(_("Search in packages description (even slower search)"))
/usr/lib/linuxmint/mintinstall/mintinstall.py:804: PyGTKDeprecationWarning: Using positional arguments with the GObject constructor has been deprecated. Please specify keyword(s) for "label" or use a class specific constructor. See: https://wiki.gnome.org/PyGObject/InitializerDeprecations
  self.refresh_cache_menuitem = Gtk.MenuItem(_("Refresh the list of packages"))
/usr/lib/linuxmint/mintinstall/mintinstall.py:814: PyGTKDeprecationWarning: Using positional arguments with the GObject constructor has been deprecated. Please specify keyword(s) for "label" or use a class specific constructor. See: https://wiki.gnome.org/PyGObject/InitializerDeprecations
  about_menuitem = Gtk.MenuItem(_("About"))
/usr/lib/linuxmint/mintinstall/mintinstall.py:897: PyGIDeprecationWarning: GObject.idle_add is deprecated; use GLib.idle_add instead
  GObject.idle_add(self.finished_loading_packages)
/usr/lib/linuxmint/mintinstall/mintinstall.py:900: PyGIDeprecationWarning: GObject.idle_add is deprecated; use GLib.idle_add instead
  GObject.idle_add(self.process_unmatched_packages)
MintInstall: Deleting old screenshots
MintInstall: No new reviews

** (mintinstall.py:16551): WARNING **: 21:43:51.798: Found icon of unknown type, skipping it: unknown
/usr/lib/linuxmint/mintinstall/mintinstall.py:1266: PyGIDeprecationWarning: GObject.timeout_add is deprecated; use GLib.timeout_add instead
  self.search_changed_timer = GObject.timeout_add(175, self.on_search_changed, entry)
/usr/lib/linuxmint/mintinstall/mintinstall.py:1875: PyGIDeprecationWarning: GObject.idle_add is deprecated; use GLib.idle_add instead
  self.search_idle_timer = GObject.idle_add(idle_search_one_package, list(listing))
/usr/lib/python3/dist-packages/mintcommon/installer/_flatpak.py:264: Warning: invalid unclassed pointer in cast to 'AsComponent'
  comps = pool.get_components_by_id(name + ".desktop")
/usr/lib/python3/dist-packages/mintcommon/installer/_flatpak.py:270: Warning: invalid unclassed pointer in cast to 'AsComponent'
  comps = pool.get_components_by_id(name)
/usr/lib/python3/dist-packages/mintcommon/installer/_flatpak.py:264: Warning: g_object_ref: assertion 'G_IS_OBJECT (object)' failed
  comps = pool.get_components_by_id(name + ".desktop")
/usr/lib/python3/dist-packages/mintcommon/installer/_flatpak.py:264: Warning: g_object_unref: assertion 'G_IS_OBJECT (object)' failed
  comps = pool.get_components_by_id(name + ".desktop")
/usr/lib/python3/dist-packages/mintcommon/installer/_flatpak.py:268: Warning: invalid unclassed pointer in cast to 'AsComponent'
  comps = pool.get_components_by_id(ALIASES[name] + ".desktop")
/usr/lib/python3/dist-packages/mintcommon/installer/_flatpak.py:270: Warning: g_object_ref: assertion 'G_IS_OBJECT (object)' failed
  comps = pool.get_components_by_id(name)
/usr/lib/python3/dist-packages/mintcommon/installer/_flatpak.py:270: Warning: g_object_unref: assertion 'G_IS_OBJECT (object)' failed
  comps = pool.get_components_by_id(name)
**
GLib:ERROR:../../../glib/ghash.c:377:g_hash_table_lookup_node: assertion failed: (!g_atomic_ref_count_compare (&hash_table->ref_count, 0))
`

**Comment by BraveSentry** [comment]
A very similar thing happens to me on Mint 19.3, Cinnamon 4.4.8

Please note that this happens not on every search. Searching for "xsca" works fine. "tea" will crash.

---- Console output of mintinstall is below ----

`MintInstall: Detected system architecture: 'x86_64'
Installer: User pkgcache is most recent, using it.
MintInstall: Deleting old screenshots
MintInstall: No new reviews
**
GLib:ERROR:../../../../glib/ghash.c:377:g_hash_table_lookup_node: assertion failed: 
(hash_table->ref_count > 0)

**Comment by mtwebster** [comment]
Does it crash if you select the "Flatpak" category at startup, but *not* if you select the "Games" category?

**Comment by BraveSentry** [comment]
Yes. In fact, "Flatpak" is the only category that produces the crash. That, and the search box.

**Comment by harlekin777** [comment]
I can confirm this bug on LMDE 4. Any progress on this issue?

**Comment by ritzip** [comment]
I can confirm this bug as well, bumping this.

**Comment by mtwebster** [comment]
@ritzip This should have been fixed quite a while ago (I missed closing this issue).

What version of mint-common are you on? This was fixed in 2.1.
```
dpkg --list | grep mint-common
```

**Comment by ritzip** [comment]
Oh, I assumed it was still not fixed since i had updated all packages earlier.

I updated mint-commons and that'll fixed it, Thank you for your time.

**Comment by mtwebster** [comment]
No problem, closing this.
